// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coozuypkxbpcbivawepq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvb3p1eXBreGJwY2JpdmF3ZXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTE4MjMsImV4cCI6MjA2MjgyNzgyM30.VOp8XYqyyIiFu4_hGW7PBN3j6q9QAUJB0u7L796IheM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});